### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Celtic-Knot** [leiyunkang7/vscode-extension-wakeonlan#1]
Hello LeiYunKang - 

Please can you translate into English, the three parts that appear in Explorer:

![ksnip_20210511-220801](https://user-images.githubusercontent.com/52403502/117885170-6d6add00-b2a5-11eb-9cc4-967f49090793.png)

Thank you!

(It's beautifully simple, and it works, but translation would be lovely, thanks.)

**Comment by leiyunkang7** [comment]
很高兴这个插件对你有用,
国际化支持已发布在v.0.0.3版本
---
I am very happy that this plugin is useful for you,
Internationalization support has been released in version v.0.0.3

https://github.com/leiyunkang7/vscode-extension-wakeonlan/commit/47407ae5c61dd6caebd37c1e8e0f85b7b2772047

**Comment by Celtic-Knot** [comment]
Perfect - thank you so much.
